### ISSUE TITLE
Having trouble getting this to work. 

### ISSUE THREAD

**Issue by dlgombert** [kota65535/openapi-merger#23]
Tried different variations, but ultimately end up with a similar response:
```
openapi-merger.cmd  -i api.pre.yml -o Testrun.yml --debug true
params:  {                                                                                                           
  input: 'api.pre.yml',                                                                                     
  output: 'Testrun.yml',                                                                                             
  config: undefined                                                                                              
  debug: true                                                                                                        
}                                                                                                                    
TypeError: Cannot read property 'value' of undefined                                                                 
    at C:\ProgramData\nvm\v14.11.0\node_modules\openapi-merger\src\util.js:12:50                                     
    at Array.every (<anonymous>)                                                                                     
    at sliceObject (C:\ProgramData\nvm\v14.11.0\node_modules\openapi-merger\src\util.js:10:19)                       
    at ComponentManager.create (C:\ProgramData\nvm\v14.11.0\node_modules\openapi-merger\src\components.js:47:15)     
    at ComponentManager.getOrCreate (C:\ProgramData\nvm\v14.11.0\node_modules\openapi-merger\src\components.js:58:23)
    at Merger.handleRef (C:\ProgramData\nvm\v14.11.0\node_modules\openapi-merger\src\merger.js:111:32)               
    at Merger.mergeRefs (C:\ProgramData\nvm\v14.11.0\node_modules\openapi-merger\src\merger.js:62:20)                
    at Merger.mergeRefs (C:\ProgramData\nvm\v14.11.0\node_modules\openapi-merger\src\merger.js:68:35)                
    at Merger.mergeRefs (C:\ProgramData\nvm\v14.11.0\node_modules\openapi-merger\src\merger.js:68:35)                
    at processTicksAndRejections (internal/process/task_queues.js:93:5)     
```         

Did you ever get this working?                                
This is the only library that really seems to do what I want.  I'd love to get it working.

**Comment by kota65535** [comment]
@dlgombert Sorry for the inconvenience. Because I've tested only on Linux and Mac, it couldn't handle Windows directory separators (backslash) correctly. I'm going to fix it soon.

**Comment by kota65535** [comment]
Hi @dlgombert, I've fixed the issue and published `0.5.0` right now.
Please try it and feel free to reopen this issue if the problem persists.
